package.json, pnpm-lock.yaml, src/pages/home/previews/video.tsx
Now video preview page can autoload .xml file matching video file name as danmu.
=> feat: add danmuku support for video preview page

README.md
=> 更新文档，端口地址修改

src/pages/manage/storages/Item.tsx, src/pages/manage/users/AddOrEdit.tsx
=> feat: add type="password" for Input

src/components/LinkWithBase.tsx, src/pages/home/folder/Search.tsx
https://github.com/alist-org/alist/issues/2907
=> fix: 修复搜索结果包含特殊符号跳转失败的BUG

src/pages/manage/backup-restore.tsx
sorry for the typo in the commit, index progress also shall not be restored as it is different on different machines
=> fix: index progress also shall not be restored

src/lang/en/home.json, src/pages/home/previews/index.ts, src/pages/home/previews/ipa.tsx, src/pages/login/index.tsx, src/utils/icon.ts
The two-line button UI is not good-looking. Merge the login SSO login button into the first line
=> fix:Incorporate the login SSO login button to the first row

src/lang/en/tasks.json, src/pages/manage/tasks/Aria2.tsx, src/pages/manage/tasks/Copy.tsx, src/pages/manage/tasks/Qbit.tsx, src/pages/manage/tasks/Task.tsx, src/pages/manage/tasks/Tasks.tsx
新增仅清除成功记录和出错重试选项
同步[alist/pull/3856](https://github.com/alist-org/alist/pull/3856)
=> feat(task): add clear succeeded and retry

src/pages/home/previews/info.tsx
follow [alist/pull/3927](https://github.com/alist-org/alist/pull/3927) to use thumbnails on file download page
=> feat: use thumb on download page

src/lang/en/drivers.json, src/lang/en/storages.json
Working with [alist-org/alist #3924](https://github.com/alist-org/alist/pull/3924).
=> Add messages for sign button [Local]

src/lang/en/br.json, src/pages/manage/backup-restore.tsx, src/pages/manage/users/AddOrEdit.tsx
Allow users to override the settings with button (will also run backup if override is enabled in case something important is overrode)
=> feat: backup and restore support override

src/lang/en/home.json, src/pages/home/toolbar/RecursiveMove.tsx
- Modify the UI for recursive movement operation and add a secondary confirmation dialog
=> feat(drivers): Modify the UI for recursive movement

src/components/ModalTwoInput.tsx, src/lang/en/home.json, src/pages/home/toolbar/RegexRename.tsx, src/pages/home/toolbar/RenameItem.tsx, src/types/obj.ts
=> feat(drivers): Preview for regexp rename

src/components/Base.tsx, src/lang/en/home.json, src/pages/home/folder/Search.tsx, src/utils/api.ts
Supports only file search or only dir search
=> feat(search):Supports file search or dir search

src/pages/home/previews/audio.tsx
=> feat: audio player use list order by default

src/pages/home/previews/video.tsx
When a subtitle file contains two languages at the same time, only one is displayed.
=> feat:add subtitles toggle options

src/pages/home/previews/aliyun_video.tsx, src/pages/home/previews/video.tsx
closes https://github.com/alist-org/alist/issues/5839
=> feat(aliyun_video_previewer): prev / next button and persistent full_screen stat

src/pages/home/previews/aliyun_video.tsx, src/pages/home/previews/video.tsx
=> style: better subtitle select

package.json, pnpm-lock.yaml, src/lang/en/br.json, src/pages/manage/backup-restore.tsx
=> feat: encrypted backup and restore

package.json, pnpm-lock.yaml, src/pages/home/previews/text-editor.tsx
https://github.com/alist-org/alist/issues/6098
=> fix: needless editor reload on content change

src/hooks/useDownload.ts, src/lang/en/home.json, src/pages/home/folder/context-menu.tsx, src/pages/home/toolbar/Download.tsx
m3u8 播放列表可以让本地播放器方便地播放 alist 上的剧集
=>  feat: playlist download

src/lang/en/storages.json
=> chore: add `proxy_range` `proxy_range-tips` for storages

package.json, pnpm-lock.yaml, src/pages/home/previews/index.ts, src/pages/home/previews/video360.css, src/pages/home/previews/video360.tsx
添加 360° 全景视频播放器，但是有如下缺点：
* 由于 cors 限制，需要开启本地代理或者使用解除 cors 限制插件
* 目前只支持等距柱状投影格式（Equirectangular）
=> feat: add 360 video player

package.json, pnpm-lock.yaml, src/components/EncodingSelect.tsx, src/components/Markdown.tsx, src/pages/home/previews/html.tsx, src/pages/home/previews/text-editor.tsx
Automatically detect the text encoding for preview and set it as the default encoding choice.
=> feat: auto detect encoding for text preview

src/pages/manage/tasks/Tasks.tsx
frontend part of AlistGo/alist#7637
Change the behavior of “do with selected tasks” from individually calling the API for each task to making a single call with all task IDs passed in at once.
=> perf(task): merge requests of operating selected

src/lang/en/tasks.json, src/pages/manage/tasks/Task.tsx, src/pages/manage/tasks/Tasks.tsx, src/types/task.ts
Frontend part of AlistGo/alist#7655
Task manage page add column `Speed` which means data transfer speed
Task manage page add detail row `Time Elapsed` which means task duration
Resize the task operation button to `sm` size
=> feat(task): add speed monitor

src/pages/manage/storages/Item.tsx, src/types/item_type.ts
Frontend part of AlistGo/alist#7677
Add a new storage addition type `Float`
=> fix(115): support float QPS

src/types/user.ts
Frontend part of AlistGo/alist#7705
=> fix(permission): enhance the strictness of permissions

src/pages/home/folder/List.tsx
- Drag files over the list to show upload dialog
- 拖动文件到列表自动弹出上传窗口
close: https://github.com/AlistGo/alist-web/issues/198
=> feat(upload): drag over list to upload

src/components/FolderTree.tsx, src/components/ModalInput.tsx, src/lang/en/home.json, src/pages/home/toolbar/CopyMove.tsx, src/pages/home/toolbar/NewFile.tsx, src/pages/home/toolbar/Rename.tsx, src/pages/home/uploads/Upload.tsx, src/pages/home/uploads/form.ts, src/pages/home/uploads/stream.ts, src/pages/home/uploads/types.ts, src/utils/api.ts
Add `overwrite existing` option to preventing unintentional data loss.
增加『覆盖已有文件』选项以防止意外的数据丢失。
=> feat(fs): add `overwrite existing` option to preventing unintentional overwriting

src/lang/en/home.json, src/pages/home/toolbar/BatchRename.tsx, src/pages/home/toolbar/Rename.tsx, src/pages/home/toolbar/Right.tsx
- Automatically use the batch rename tool when renaming multiple selected objects.
- 重命名多个选中对象时，自动使用批量重命名工具。
=> feat(batch-rename): batch rename for multiple selected objs

src/components/Paginator.tsx
Add a dropdown paginator for efficient pagniation.
增加下拉分页器以方便跳转到任意分页。
Inspired by: @j2rong4cn https://github.com/AlistGo/alist-web/pull/179
参考自： @j2rong4cn https://github.com/AlistGo/alist-web/pull/179
close: https://github.com/AlistGo/alist-web/pull/179
close: https://github.com/AlistGo/alist/issues/6515
=> feat(pagination): add a dropdown paginator for efficient pagniation

src/pages/manage/tasks/Task.tsx
Front-end part of AlistGo/alist#7852
=> feat(task): allow retry canceled

src/lang/en/home.json, src/pages/home/toolbar/CopyMove.tsx, src/pages/home/toolbar/NewFile.tsx, src/pages/home/toolbar/RecursiveMove.tsx, src/pages/home/toolbar/Rename.tsx, src/pages/home/uploads/Upload.tsx, src/utils/api.ts
Advanced conflict policy for preventing unintentional overwriting:
增加冲突策略选项以防止意外的数据丢失。
Cancel if file exists
如果文件已存在，则取消操作
Overwrite existing files
覆盖已存在文件
Skip existing files
跳过已存在文件
Front-end part of: https://github.com/AlistGo/alist/pull/7906
=> feat(recursive-move): Advanced conflict policy for preventing unintentional overwriting

src/lang/en/settings.json, src/pages/home/previews/index.ts
Front-end part of AlistGo/alist#7984
=> feat(archive): support deprioritize previewing

src/pages/login/index.tsx
This PR implement conditional webauthn login and ensures compatibility with older browsers.
> Conditional webauthn login displays a credential selection UI only if the user has a [discoverable credential](https://github.com/w3c/webauthn/wiki/Explainer:-WebAuthn-Conditional-UI#discoverable-credential) registered with the [Relying Party](https://github.com/w3c/webauthn/wiki/Explainer:-WebAuthn-Conditional-UI#relying-party) on their authenticator. The credential is displayed alongside autofilled passwords. This solves the bootstrapping problem when replacing traditional username and password with WebAuthn: websites can fire a WebAuthn call while showing a regular password prompt without worrying about showing a modal dialog error if the device lacks appropriate credentials. …
=> feat(webauthn): implement conditional login

package.json, pnpm-lock.yaml, src/components/ModalInput.tsx, src/pages/home/toolbar/OfflineDownload.tsx
https://github.com/user-attachments/assets/6cd50104-fd20-48c9-834b-3fe02f4729ac
=> feat(offline-download): add support for dropping torrent files to generate magnet links

src/pages/home/Obj.tsx, src/store/history.ts
Fix history scroll caching issue. (https://github.com/AlistGo/alist-web/pull/256#issuecomment-2709526124)
修复滚动条历史缓存问题。(https://github.com/AlistGo/alist-web/pull/256#issuecomment-2709526124)
=> fix(history): fix history scroll caching issue

src/pages/home/previews/archive.tsx
=> fix(archive): extract encode password

src/hooks/usePath.ts, src/hooks/useRouter.ts, src/pages/home/Obj.tsx, src/pages/manage/tasks/helper.tsx, src/store/history.ts
- Fix history caching in "Load more" or "Auto load more" mode
- 修复『加载更多』和『自动加载更多』模式下，历史缓存失效问题
- Fix selection state lost in history caching
- 修复历史缓存的选中状态丢失问题（多选后，打开新页面，返回，选中状态应该保持）
=> fix(history): fix history caching

src/pages/home/previews/index.ts, src/pages/home/toolbar/Center.tsx, src/pages/home/toolbar/Decompress.tsx, src/store/archive.ts, src/utils/api.ts, src/utils/icon.ts
Frontend part of AlistGo/alist#8184.
=> feat(archive): support multipart archives

src/pages/login/index.tsx
Add signal of `AbortController` for webauthn login flows including conditional webauthn login and manual webauthn login.
Docker image for test: `mmx233/alist:frontend-20250326`
fixed https://github.com/AlistGo/alist/issues/8207
=> feat(webauthn): implement multi login flow control

src/pages/home/Body.tsx
Update Body to Include index.md in Rendering
=> feat: Default rendering index.md

src/utils/handle_resp.ts
修复错误 https://github.com/AlistGo/alist/issues/8249
复现
1. 管理员登录
2. 管理界面，右上角，退出登录
3. 游客登录
=> fix(url): add location.pathname check，prevent duplicate jumps

src/pages/home/previews/audio.css, src/pages/home/previews/audio.tsx
- 自动查找封面图片（同名文件 > front.* > cover.* > folder.*
- 主题、颜色跟随 Alist
- 支持 Media Session API，支持使用系统控制（SMTC）
=> feat(audio): auto find cover and support Media Session API

src/pages/manage/users/AddOrEdit.tsx
fix: https://github.com/AlistGo/alist/issues/9224
=> refactor(AddOrEdit.tsx): Implement role-based path selection
