AlistGo/alist-web

- src/pages/home/folder/Search.tsx
- src/pages/home/header/Header.tsx
- src/utils/compatibility.ts
If Mac is detected, additionally allow `Cmd`+`K` as the keyboard shortcut for toggling the search popup.
> feat: use Cmd+K for search on Mac

- src/pages/home/previews/aliyun_video.tsx
Due to switching video connections with different resolutions, subtitles are lost
> Fixed subtitle loss when switching videos with different resolutions

- src/pages/home/previews/index.ts
By default, plain html file now rendered by **Markdown**, it would be easier to use if the **HTML render** as the first preview engine
> feat: preview plain html file by HTML render first

- src/components/ModalInput.tsx
- src/pages/home/toolbar/Rename.tsx
- src/utils/notify.tsx
在某些情形下，如设置站点公告为一小段非标题文字且长度较长：
就会出现如图，关闭按钮和文字重合的问题。
修复后：
仅在 `.` 出现在非第一个（如 `.DS_Store` 就全选中）、并且是文件（而非文件夹）、并且是重命名窗口才会触发。
> fix(Notify): 修复关闭按钮和文字重合的问题 & feat(Rename): 重命名时默认选中后缀名前的部分

- src/pages/home/folder/Search.tsx
> fix: Incorrect current page of search paginator

- public/static/epub.js/viewer.html
`jsdelivr` 在使用时连接不太稳定，就更换为`elemecdn`
- 比对了文件`MD5` `SHA1` 都是一样的，更换链接后`integrity`应该不用更换吧？
>文件:eml-0.3.93-ele-epub.min.js **(新)**
大小: 223875 字节
MD5: 0C49D4A46630BF7864E5E1B74DB07914
SHA1: 0C1C526BA0699BDFEEE72F52E9993DB68D70B262
CRC32: 5FFFB62E
>
>文件: jsd-0.3.93-jsd-epub.min.js **(旧)**
大小: 223875 字节
MD5: 0C49D4A46630BF7864E5E1B74DB07914
SHA1: 0C1C526BA0699BDFEEE72F52E9993DB68D70B262
CRC32: 5FFFB62E
>文件: elm-jszip.min.js **(新)**
大小: 97630 字节
MD5: B5D02B3F0BF3AE026451909419DF07BB
SHA1: C96375D50E72B199AA54DE7B9AD908FD5A2DC7BC
CRC32: D538C831
>
>文件: jsd-jszip.min.js **(旧)**
大小: 97630 字节
MD5: B5D02B3F0BF3AE026451909419DF07BB
SHA1: C96375D50E72B199AA54DE7B9AD908FD5A2DC7BC
CRC32: D538C831
> Modify epub static resource link

- src/pages/home/previews/aliyun_video.tsx
- src/pages/home/previews/video.tsx
- src/pages/home/previews/video_box.tsx
#134 相关，对视频加载失败的情况做下处理，重写了容器高度计算逻辑
> fix: set height when failed to load video

- src/pages/home/previews/aliyun_video.tsx
修复 issue [6045](https://github.com/alist-org/alist/issues/6045)
artplayer 调用 switchUrl 后，原本暂停的视频会播放
> fix: paused video will play automatically after switching url

- src/lang/en/home.json
- src/pages/home/folder/ListItem.tsx
- src/pages/home/toolbar/LocalSettings.tsx
- src/store/local_settings.ts
Make long file scrollable with hidden scrollbar. tested on latest firefox and chrome, safari
> feat: make long file name scrollable

- src/pages/home/folder/GridItem.tsx
- src/pages/home/folder/ImageItem.tsx
- src/pages/home/folder/ListItem.tsx
相关 issue [#5989](https://github.com/alist-org/alist/issues/5989) [#6021](https://github.com/alist-org/alist/issues/6021)
具体改动如下
- 在显示多选框时，优先触发选择操作，防止跳进更深层的文件夹里
演示效果如下
https://github.com/alist-org/alist-web/assets/55272688/ad24f37c-fbae-44c4-bebe-3d0dcfda1e18
https://github.com/alist-org/alist-web/assets/55272688/9c724c4b-4cce-40bb-8824-2343488631ef
> feat: block actions of router while checkbox enabled

- src/components/Markdown.tsx
refer to https://github.com/alist-org/alist-web/pull/150#issuecomment-1964282300
改动如下
- Markdown 大纲栏改为默认不显示
> fix: disable markdown toc on default

- src/pages/home/folder/GridItem.tsx
- src/pages/home/folder/ImageItem.tsx
- src/pages/home/folder/ListItem.tsx
- src/pages/home/folder/helper.ts
- src/store/local_settings.ts
refer to https://github.com/alist-org/alist-web/pull/151#issuecomment-1970458436
- 补充修改：`网格模式` 和 `图片模式` 下，启用复选框时直接打开的逻辑
- 补充修改：`open_item_on_checkbox` 的 `with_ctrl` 选项
> fix: additional logic of optional open item on checkbox

- package.json
- pnpm-lock.yaml
- src/app/theme.ts
- src/lang/en/home.json
- src/pages/home/folder/Grid.tsx
- src/pages/home/folder/GridItem.tsx
- src/pages/home/folder/ImageItem.tsx
- src/pages/home/folder/Images.tsx
- src/pages/home/folder/List.tsx
- src/pages/home/folder/ListItem.tsx
- src/pages/home/folder/context-menu.tsx
- src/pages/home/folder/helper.ts
- src/store/local_settings.ts
改动如下
- 新增本地配置 `在复选框关闭时使用鼠标框选`
- 启用鼠标框选功能时（使用 [@viselect/vanilla](https://github.com/simonwep/selection/tree/master/packages/vanilla) 实现）
- 在 `.obj-box` 里可以鼠标滑动框选文件及文件夹
- 支持按住 `ctrl/command` 键可以进行额外单选切换
- 支持按住 `shift` 键可以进行范围选择（以上次点击为起点，以这次点击为终点，该功能原本就支持 [代码逻辑](https://vscode.dev/github/liuycy/alist-web/blob/better-interaction/src/store/obj.ts#L122)）
- 修复之前版本在 `网格模式` 下直接预览图片失效问题
- 选中多个文件时，右键菜单改为与 复选框 底部工具栏提供的功能 一致，选中单个保持不变
演示效果如下
https://github.com/alist-org/alist-web/assets/55272688/5eb4ce9d-5e82-45ad-91c0-2092857da2a8
多选右键菜单如下
> feat: select with mouse while checkbox closed

- src/components/FolderTree.tsx
- src/hooks/useUtil.ts
- src/pages/home/Sidebar.tsx
refer to https://github.com/alist-org/alist-web/pull/146#issuecomment-1975062111
改动如下:
- 目录树组件加了段逻辑，用来隐藏全局配置中正则匹配到的目录
- 加了个 prop `showHiddenFolder` 用来区分 `侧边栏` 和 `移动/复制` 操作里的目录树
- 通过路径栏直接访问隐藏文件夹时，侧边栏会显示该文件夹（跳出后自动隐藏）
演示效果:
https://github.com/alist-org/alist-web/assets/55272688/a2eca4ff-d689-4d52-a923-f2bad4b68803
视频中使用的正则:
```
/\/README.md/i
/\/hide_folder_and_subfolder/i
/\/only_hide_parent_folder$/i
```
> fix: hide matched files/folders in sidebar

- src/app/theme.ts
- src/lang/en/home.json
- src/pages/home/folder/Folder.tsx
- src/pages/home/folder/GridItem.tsx
- src/pages/home/folder/ImageItem.tsx
- src/pages/home/folder/List.tsx
- src/pages/home/folder/ListItem.tsx
- src/pages/home/folder/helper.ts
- src/pages/home/toolbar/LocalSettings.tsx
- src/store/local_settings.ts
修改如下
- 修复图片预览组件被 侧边栏 和 置顶按钮 遮挡问题 (z-index 问题)
- 在手机上 本地设置隐藏一些需要鼠标键盘操作的 选项
- 扩大复选框的点击范围，在手机上能更容易点到复选框
- 新增 `open_item_on_checkbox` 的选项 `disable_while_checked`
- 选中一个及以上时不打开文件夹(优先触发选择)，没有选中时打开文件夹 (参考 https://github.com/alist-org/alist-web/pull/148#issuecomment-2011539946)
复选框范围 修改前后对比
> feat: better action of checkbox on mobile phone

- src/pages/home/previews/video_box.tsx
The URL passed as query parameter for IINA will be url-encoded. This will fix `Cannot open file or stream!` showing when URL contains special characters (e.g. `/[foo] bar.mkv`) for IINA.
This is somehow related to a bug in IINA [fix: avoid double percent-encode for url scheme](https://www.github.com/iina/iina/pull/4860), but I think it is better to do url-encoding in alist to support IINA until this bug has been resolved.
Additionally, if the filename contains a `%`, then it is expected to be encoded per URI standard. In this case, it is not an IINA bug.
> Encode URL param for external player

- src/pages/home/folder/Search.tsx
修复搜索页面的跳转链接。
触发情况:
- 文件名包含 `#` `/` `%` ` `
> fix: incorrect search results link with `#` (close alist-org/alist#6234)

- src/components/Markdown.tsx
- src/utils/path.ts
fix https://github.com/alist-org/alist/issues/6419
改动如下
- Markdown 预览组件 解析 相对路径 时 加上 `base_path`
- 新增 `pathResolve` 工具函数，将类似 `./a` `../a` `a/../b` 的路径转成绝对路径
> fix: base path for relative path in markdown

- src/lang/en/drivers.json
- src/pages/home/previews/audio.tsx
Related to https://github.com/alist-org/alist/pull/6423
改动如下:
- 兼容驱动
- 获取可显示的封面
- 获取并显示可用的歌词
> feat: add supports for netease music driver

- src/components/FolderTree.tsx
fix https://github.com/alist-org/alist/issues/6428
refer to https://github.com/alist-org/alist/issues/6428#issuecomment-2107176544
改动如下:
- `复制` `移动` `聚合移动` 的弹窗组件 `ModalFolderChoose` 正确显示 并 展开到 已选择的文件夹
https://github.com/alist-org/alist-web/assets/55272688/8a64570b-9d7a-49b2-a274-2bc7130f0962
> fix: show last selected folder on copy/move modal

- src/pages/home/header/Header.tsx
将搜索框对 背景/颜色 大小 与右侧按钮进行统一
- 左侧为修改后，右侧为修改前
> style: Search Box

- package.json
- src/pages/home/Footer.tsx
- src/store/settings.ts
我是因 https://github.com/alist-org/alist-web/blob/972fcf5e2dbf7c0e72e59baf16b1e6173d4a1546/src/pages/home/Footer.tsx#L13 而注意到这一点的
相关的PR还包括：
* https://github.com/alist-org/alist/pull/6007
> docs: change outdated repository link to alist-org

- src/app/index.css
- src/pages/manage/storages/Item.tsx
1. iOS 14 DropDown下拉选项高度丢失，添加`flex-shrink: 0`后解决
3. iOS 14.8 输入法导致输入内容重复
https://github.com/user-attachments/assets/41bd365a-6846-4d19-a5ee-1237ae26db13
> 修复iOS14若干问题

- src/pages/manage/sidemenu_items.tsx
- src/pages/manage/tasks/Task.tsx
- src/pages/manage/tasks/Tasks.tsx
- src/types/task.ts
This pull request is the frontend part of AlistGo/alist/#7398
1. Add a creator attribute to the upload, copy and offline download tasks, so that a GENERAL task creator can view and cancel them. The creator will be displayed over the task state in the form of a Badge.
2. Transfer call on `/admin/task` to `/task`.
> feat: support general users view and cancel own tasks

- src/lang/en/tasks.json
- src/pages/manage/tasks/Aria2.tsx
- src/pages/manage/tasks/Copy.tsx
- src/pages/manage/tasks/Qbit.tsx
- src/pages/manage/tasks/Task.tsx
- src/pages/manage/tasks/Tasks.tsx
- src/pages/manage/tasks/Upload.tsx
- src/pages/manage/tasks/helper.tsx
- src/pages/manage/tasks/offline_download.tsx
- src/pages/manage/users/AddOrEdit.tsx
Simplify and arrange task details
Add the feature to select tasks and retry/delete them in batches
Add a regex matcher to filter tasks
Support sorting tasks by name, creator, state or progress
Support redirecting to paths of files operated
Closes AlistGo/alist#7184
Closes AlistGo/alist#7096
> feat: enhance task manage page

- src/components/Markdown.tsx
修复Markdown中内置base64编码图片的解析错误问题
老版本是支持的，新版本增加对直链的支持后，导致base64编码图片解析出错。
不支持的Markdown文件特征如下：
> fix: Markdown base64编码图片支持

- src/lang/en/manage.json
- src/lang/en/settings.json
- src/lang/en/users.json
- src/pages/manage/sidemenu_items.tsx
- src/types/setting.ts
- src/types/user.ts
frontend part of AListGo/alist#7634
Add two permissions.
Add a page to configure FTP server.
> feat: ftp server support

- src/pages/home/folder/context-menu.tsx
add z-index to the context menu to avoid being obstructed by the nav bar
为右键菜单添加额外的z-index来避免导航栏的遮挡
reason：
When the "position of header & nav bar" option is set to anything other than normal, the nav bar will overlay the context menu.
原因：设置“标题栏和导航栏的位置”为除了“普通”以外的选项时, 导航栏会遮挡右键菜单
Any suggestions are appreciated.
第一个pr，有问题还请大神指点。
> fix: add z-index to context menu

- src/store/obj.ts
By default, `naturalSort` sort strings with case sensitive, which means A-Za-z.
This change aligns the sort behavior with Linux and Windows, which is Aa-Zz.
> chore: ignore case when sort

- src/components/Markdown.tsx
在 Markdown 预览中添加 Mermaid 图表支持
目前 `solid-markdown` 渲染代码块中的 mermaid 的结果如下：
```html
<pre key="pre-75-1-38"><code class="language-mermaid" key="code-75-1-0">flowchart TD
A[Christmas] --&gt;|Get money| B(Go shopping)
B --&gt; C{Let me think}
C --&gt;|One| D[Laptop]
C --&gt;|Two| E[iPhone]
C --&gt;|Three| F[fa:fa-car Car]
</code></pre>
```
通过 CDN 引入 mermaid  js，使用 `mermaid.run()` 对 `language-mermaid` 执行渲染
官方文档参考: <https://mermaid.js.org/config/usage.html>
为避免增加项目的构建体积，此处选择通过 CDN 来引入 Mermaid.js 库，而不是通过 NPM 包管理器安装（会给 dist 增加 3-5 MB 的体积）
如果存在任何潜在的问题或改进建议，请随时提出讨论
> feat: markdown mermaid support

- src/lang/en/storages.json
Front-end part of: https://github.com/AlistGo/alist/pull/7730
Allow users to disable storage indexing.
允许用户禁用存储索引。
> feat(index): add `disable index` option for storages

- src/pages/home/previews/video.tsx
The video continues loading even after leaving the video page, set the `src` attribute to an empty string to stop loading process.
离开视频页面后视频请求仍会继续加载占用带宽，把 `src` 属性设置为空字符串来停止加载。
> fix(web): cancel video loading after leaving the video page

- src/hooks/usePath.ts
- src/utils/api.ts
Fix: going to a new page before the obj request is done, the obj may be shown in the new page.
修复：当前 obj 请求完成之前进入新的页面，可能导致新的页面显示的是原 obj。
> fix(request): abort obj request after going to new path

- src/hooks/usePath.ts
- src/store/scroll.ts
Fix: when the `Pagination type` is set to `Load more` or `Auto load more`:
修复：当『分页类型』为『加载更多』或『自动加载更多』时：
- After a refresh (e.g., rename, delete, etc.), only the current page is loaded, should load the current page and all preceding pages.
- 内容刷新后（如：重命名、删除等），只有当前分页内容会被加载，应当加载当前页及之前的所有页面。
> fix(pagination): fix incorrect pagination after refreshing

- src/lang/en/settings.json
- src/lang/en/settings_other.json
- src/pages/manage/settings/Other.tsx
- src/pages/manage/sidemenu_items.tsx
- src/pages/manage/tasks/helper.tsx
Front-end part of https://github.com/AlistGo/alist/pull/7716
> feat(offline-download): allow using offline download tools in any storage

- src/pages/home/toolbar/RecursiveMove.tsx
- src/utils/api.ts
Add overwrite option for recursive move to preventing unintentional overwriting.
为聚合移动增加『覆盖已有文件』选项以防止意外的数据丢失。
Front-end part of: https://github.com/AlistGo/alist/pull/7868
> feat(recursive-move): add `overwrite` option to preventing unintentional overwriting

- src/pages/home/previews/video.tsx
关闭了 html 标签的转义。这对于正确解析 VTT 字幕是必要的。例如，一个规范的 VTT 字幕经常带有说话人的信息，但在播放器解析时，会自动转义 html 标签，导致输出的字幕不正常。
以 [https://www.w3.org/TR/webvtt1/#introduction-caption](https://www.w3.org/TR/webvtt1/#introduction-caption) 中的字幕为例，对于
```
WEBVTT
00:11.000 --> 00:13.000
<v Roger Bingham>We are in New York City
```
现在会解析成`<v Roger Bingham>We are in New York City`，正确的解析应该是`We are in New York City`
> fix(video): correct VTT subtitle styling in preview

- src/hooks/usePath.ts
Fix the issue that loading screen persists when object is not found.
修复当对象不存在时，页面一直保持 Loading 状态。
close: https://github.com/AlistGo/alist/issues/7333
> fix(error): fix issue that loading screen persists when object is not found

- src/components/Base.tsx
- src/hooks/usePath.ts
- src/hooks/useRouter.ts
- src/pages/home/Obj.tsx
- src/pages/home/folder/Pager.tsx
- src/store/history.ts
When `Pagination Type` is `Pagination`:
当『分页类型』为『分页』时：
- Support navigating back/forward to history pages
- 支持浏览器前进/后退到历史分页
- Cache history data for pagniations to reduce requests and improve performance
- 缓存分页的历史数据以减少重复请求，提升性能
> refactor(pagination): support navigating to history page in `Pagination` mode

- src/pages/home/previews/video.tsx
Destroy flv player & hls player after cleaning up to cancel video loading.
离开页面时清理 FLV 播放器 及 HLS 播放器，以停止视频持续加载。
> fix(video): destroy flv player & hls player after cleaning up

- src/pages/home/toolbar/BatchRename.tsx
Supports using wildcards for batch renaming.
支持在批量重命名时使用通配符。
- {created_year}
- {created_month}
- {created_date}
- {created_hour}
- {created_minute}
- {created_second}
- {modified_year}
- {modified_month}
- {modified_date}
- {modified_hour}
- {modified_minute}
- {modified_second}
> feat(batch-rename): supports using wildcards for batch renaming

- src/hooks/usePath.ts
- src/lang/en/tasks.json
- src/pages/home/Obj.tsx
- src/pages/manage/tasks/Copy.tsx
- src/pages/manage/tasks/Task.tsx
- src/pages/manage/tasks/helper.tsx
- src/store/history.ts
修复任务页面点击路径进行跳转时，文件夹内容会保持为上一次访问的文件夹的内容的问题。不知道是 #226 还是 #246 的问题，总之提前了记录历史的时机（从离开页面时到页面加载完毕时）从而修复了这个问题。
给驱动离线下载的源路径添加了跳转功能。
> fix(task): invalid path redirect

- src/lang/en/home.json
- src/pages/home/folder/Grid.tsx
- src/pages/home/folder/GridItem.tsx
- src/pages/home/folder/ImageItem.tsx
- src/pages/home/folder/Images.tsx
- src/pages/home/folder/List.tsx
- src/pages/home/folder/ListItem.tsx
- src/pages/home/folder/helper.ts
- src/store/local_settings.ts
- src/store/obj.ts
Checkboxes and drag selection are both used for multiple selection, while both of them are very useful, they are incompatible with each other, making the options and states complex.
复选框和拖拽选择的目的都是为了多选，这两者都很有用，但它们互相之间不兼容，导致相关选项和状态复杂。
- Compatible with checkbox and drag selection
- 兼容复选框及拖拽选择
- Preserve selection state when navigating between pages
- 页面切换时保持选中状态
- Fix issues with drag selection state
- 修复拖拽选择状态问题
- Fix selection behaviour with `Shift` key
- 修复按下 `Shift` 键时的选择表现
- Simplify checkbox & drag selection options
- 简化复选框、拖拽选择选项
> refactor(selection): refactor checkbox & drag selection

- package.json
- pnpm-lock.yaml
- vite.config.ts
- 更新 vite 至 v4
- 处理 更新后 solid-icons 报错问题
v5、v6 可能与现有包版本差距较大，v4 比较接近现有包的版本，且 v4 相比 v3 构建速度有提升，v4 最近仍有更新，因此选择 v4
Related: https://github.com/AlistGo/alist-web/pull/133 https://github.com/AlistGo/alist-web/pull/190 https://github.com/AlistGo/alist/discussions/6253
> chore(deps): update dependency vite to v4

- src/pages/login/index.tsx
Change token to `undefined` will cause sso not able to set valid tokens. But in another hand if we have a invalid token, we will also get errors in conditional webauthn login flow, so we need to modify webauthn api for this.
fixes:
- https://github.com/AlistGo/alist/issues/8283
- https://github.com/AlistGo/alist/issues/8165
> fix(sso): webauthn conditional login is not compatible with sso

- src/pages/login/index.tsx
Fixed for following senarios:
- Webauthn login is not canceled after page exit.
- Conditional webauthn login is running even webauthn is not enabled.
Image for test: `mmx233/alist:frontend-20250416`
May fix:
- https://github.com/AlistGo/alist/issues/8339
> fix(authn): cancel webauthn login on clean up

- src/components/Markdown.tsx
检测 Markdown 内容是否包含公式，动态导入 `remark-math` 和 `rehype-katex`，以便减小首页 js 的体积。
由于浏览数学公式并非常见需求，且 https://github.com/AlistGo/alist/pull/7923 引入的默认启用的服务端渲染 Markdown 会使数学公式无法渲染，修改为动态导入能够最多节约服务器 20% 的流量。
下面是在 main 分支和本 pr 分支两次打包的对比
Before:
After:
Before:
```powershell
D:\temp\alist-web [md +1 ~4 -0 !]> pnpm build        
> alist-web@0.0.0 build D:\temp\alist-web
> vite build
vite v4.5.13 building for production...
✓ 884 modules transformed.
[plugin:vite:reporter]
(!) D:/temp/alist-web/src/pages/home/previews/download.tsx is dynamically imported by D:/temp/alist-web/src/pages/home/previews/index.ts but also statically imported by D:/temp/alist-web/src/pages/home/file/File.tsx, dynamic import will not move module into another chunk.
dist/assets/item_type-legacy.1b6076a1.js …
```
> perf: lazy load for math rendering

- src/pages/home/previews/audio.tsx
补充：https://github.com/AlistGo/alist-web/pull/271
> fix(audio): ensure cover image falls back to thumbnail if available

- src/pages/home/previews/aliyun_video.tsx
- src/pages/home/previews/video.tsx
修复 https://github.com/AlistGo/alist-web/pull/269 引入的 BUG。截图和跨域只能二选一，加入错误事件处理，尝试在错误时取消 `crossOrigin` 参数。
Close: https://github.com/AlistGo/alist/issues/8414
> feat(video): handle player error by removing Cross-Origin attribute
